# Polkadot Validators
IC01DOT = 15zH8tbFxyBgvkAdF3UWSfykAXADbS32vJuYRHTkZJ15Y4jd
IC02DOT = 12Qq3fn9xnFZ37Ltcj6BH8NSpAQjEMp2oKnEALa7bbuguU4L

# Kusama Validators
IC00KSM = JKupaoCtkRzMjCDQJbVMbG1jmEr8ebtoRG7cmxWkc8vM2uZ
IC01KSM = GG1fakzTavhuof7CVaZU7SJxeK1r4ndoxcCrzbgPcZ7sQDx
IC02KSM = D5aAp1y8XfkrmtPqsGFZtCjJrPZqKrsG2ceSha846jy6RMU
IC03KSM = Ed1xXhwva7tsK6sY5WnRQNVQ5bXC2kNbkpbU1EhjPZy4Cb6
IC04KSM = E3VZNd9JzQfBfh6GxMHx67b3LP8gWnJbhjZL7XPPGtCQvks
